//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musiq_Library.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public int ReleaseID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string Label { get; set; }
        public Nullable<int> NumberOfTracks { get; set; }
        public string OtherArtists { get; set; }
    }
}
